### ISSUE TITLE
Doesn't show the logs

### ISSUE THREAD

**Issue by pavliukpetro** [mihai-vlc/bm-extender#2] opened 2019-10-21 10:41 UTC
Hello, the extension doesn't show the log. I see the js error in the console.
Uncaught (in promise) TypeError: Cannot read property 'match' of undefined
    at Object.formatObjects (content.js:2)
    at l (content.js:2)
    at u (content.js:2)
    at Object.d [as setupLog] (content.js:2)
    at content.js:2

Please, fix.
Thank you.

**Comment by MMoserM** [comment] 2019-10-28 09:59
Just adding to this, the issue is caused when DWithEase extension is enabled (https://chrome.google.com/webstore/detail/ffhabonelknmejmdnekedmijlhebpcio), when i disabled DWtihEase on my browser it went back to working

**Comment by mihai-vlc** [comment] 2020-04-18 03:13
This is now fixed in 1.7.5

Please reopen the ticket if you still have issues.

**Closed as completed by mihai-vlc** 2020-04-18 03:13 UTC

**Comment by pavliukpetro** [comment] 2020-04-18 11:32
Thank you, @ionutvmi
